# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user.user_provider:
        class: UserBundle\Security\UserProvider
        arguments: [@fos_user.user_manager]


